function dpoae_gui(~,~)
global hage age hname hear mainFigure htype_range hratio hf1min hf1max hnum_points hcheck_level hlevel_f1 hlevel_f2 hnum_av hduration htype_dpoae hfs ...
    boolean_type_dpoae2 stype_dpoae boolean_type_range2 check_level hcheck_l name ear ratio f1min check_l f1max num_points level_f1 level_f2 num_av duration fs type_range type_dpoae...
    mainguiFigure

load DPDefault
close(mainguiFigure)
scrsize=get(0,'ScreenSize');
mainFigure=figure;
set(mainFigure,'OuterPosition',[0 30 scrsize(3) scrsize(4)-30])

if (strcmp(type_dpoae,'2f1-f2'))
    stype_dpoae = {'3f1-2f2' '2f1-f2'};
    boolean_type_dpoae2 = 1;
else
    stype_dpoae = {'2f1-f2' '3f1-2f2'};
    boolean_type_dpoae2 = 0;
end

if (strcmp(type_range,'logari'))
    stype_range = {'linear' 'logarithmic'};
    boolean_type_range2 = 1;
else
    stype_range = {'logarithmic' 'linear'};
    boolean_type_range2 = 0;
end

if (strcmp(ear,'left'))
   sear = {'Left' 'Right'};
else
   sear = {'Right' 'Left'}; 
end



uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.25 0.9 0.5 0.03],...
    'BackgroundColor',[84 84 84]/256,...
    'ForegroundColor','w',...
    'FontWeight','bold',...
    'Fontsize',11,...
    'String','General and Checkfit parameters:');

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.41 0.86 0.2 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Sampling frequency [Hz]:',...
    'HorizontalAlignment','center');
hfs = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.46 0.81 0.1 0.04],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(fs));
uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.51 0.77 0.2 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Length of the checkfit signal [ms]:',...
    'HorizontalAlignment','center');
hcheck_l = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.56 0.72 0.1 0.04],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(check_l));
uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.3 0.77 0.2 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Checkfit impulse level [dB SPL]',...
    'HorizontalAlignment','center');
hcheck_level = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.35 0.72 0.1 0.04],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(check_level));

% %% Patient info
% uicontrol(mainFigure,...
%     'Style','text',...
%     'Units','normalized',...
%     'Position',[0.66 0.9 0.3 0.03],...
%     'BackgroundColor',[84 84 84]/256,...
%     'ForegroundColor','w',...
%     'FontWeight','bold',...
%     'Fontsize',11,...
%     'String','Patient info:');
% 
% uicontrol(mainFigure,...
%     'Style','text',...
%     'Units','normalized',...
%     'Position',[0.72 0.86 0.2 0.03],...
%     'BackgroundColor','w',...
%     'Fontsize',11,...
%     'String','Patient ID:',...
%     'HorizontalAlignment','center');
% hname = uicontrol(mainFigure,...
%     'Style','edit',...
%     'Units','normalized',...
%     'Position',[0.72 0.81 0.2 0.04],...
%     'BackgroundColor','w',...
%     'Fontsize',11,...
%     'HorizontalAlignment','center',...
%     'String',name);
% 
% hear = uicontrol(mainFigure,...
%     'Style','popupmenu',...
%     'Units','normalized',...
%     'Position',[0.83 0.69 0.1 0.1],...
%     'BackgroundColor','w',...
%     'Fontsize',11,...
%     'String',sear,...
%     'Value',1);
% uicontrol(mainFigure,...
%     'Style','text',...
%     'Units','normalized',...
%     'Position',[0.72 0.759 0.1 0.03],...
%     'BackgroundColor','w',...
%     'Fontsize',11,...
%     'String','Ear:',...
%     'HorizontalAlignment','center');
% uicontrol(mainFigure,...
%     'Style','text',...
%     'Units','normalized',...
%     'Position',[0.72 0.72 0.1 0.03],...
%     'BackgroundColor','w',...
%     'Fontsize',11,...
%     'String','Age:',...
%     'HorizontalAlignment','center');
% hage = uicontrol(mainFigure,...
%     'Style','edit',...
%     'Units','normalized',...
%     'Position',[0.83 0.72 0.1 0.03],...
%     'BackgroundColor','w',...
%     'Fontsize',11,...
%     'HorizontalAlignment','center',...
%     'String',num2str(age));

%% DPOAE
uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.04 0.65 0.92 0.03],...
    'BackgroundColor',[84 84 84]/256,...
    'ForegroundColor','w',...
    'FontWeight','bold',...
    'Fontsize',11,...
    'String','DPOAE parameters:');

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.14 0.57 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Which type of range for the spacing of the frequencies',...
    'HorizontalAlignment','center');
htype_range = uicontrol(mainFigure,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.14 0.52 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String',stype_range,...
    'Value',2);


uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.4 0.31 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Ratio between F1 and F2:',...
    'HorizontalAlignment','center');
hratio = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.4 0.26 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(ratio));

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.14 0.44 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Frequency F1 minimum [Hz]:',...
    'HorizontalAlignment','center');
hf1min = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.14 0.39 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(f1min));

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.14 0.31 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Frequency F1 maximum [Hz]:',...
    'HorizontalAlignment','center');
hf1max = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.14 0.26 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(f1max));

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.14 0.18 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Number of frequencies F1',...
    'HorizontalAlignment','center');
hnum_points = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.14 0.13 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(num_points));

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.4 0.59 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Level of F1 [dB SPL]',...
    'HorizontalAlignment','center');
hlevel_f1 = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.4 0.54 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(level_f1));

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.4 0.44 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Number of averages:',...
    'HorizontalAlignment','center');
hnum_av = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.4 0.39 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(num_av));

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.66 0.44 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Duration of each stimuli [s]:',...
    'HorizontalAlignment','center');
hduration = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.66 0.39 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(duration));

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.66 0.31 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Which Dp is wanted',...
    'HorizontalAlignment','center');
htype_dpoae = uicontrol(mainFigure,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.66 0.26 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String',stype_dpoae,...
    'Value',2);

uicontrol(mainFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.66 0.59 0.16 0.03],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'String','Level of F2 [dB SPL]',...
    'HorizontalAlignment','center');
hlevel_f2 = uicontrol(mainFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.66 0.54 0.16 0.05],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center',...
    'String',num2str(level_f2));

%% start
startbut = uicontrol(mainFigure,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.45 0.08 0.3 0.1],...
    'Fontsize',13,...
    'FontWeight','bold',...
    'String','START',...  
    'Callback',@start_dpoae);
uicontrol(startbut) % give start button focus
% uicontrol(mainFigure,...
%     'Style','pushbutton',...
%     'Units','normalized',...
%     'Position',[0.37 0.08 0.15 0.1],...
%     'BackgroundColor',[50 205 50]/256,...
%     'Fontsize',13,...
%     'FontWeight','bold',...
%     'String','Load Settings',...  
%     'Callback',@dpoae_load_settings);  
% 
% uicontrol(mainFigure,...
%     'Style','pushbutton',...
%     'Units','normalized',...
%     'Position',[0.57 0.08 0.15 0.1],...
%     'BackgroundColor',[50 205 50]/256,...
%     'Fontsize',13,...
%     'FontWeight','bold',...
%     'String','Save Settings',...  
%     'Callback',@dpoae_save_settings);
end
function start_dpoae(~,~)

%%
% This function converts all the string parameters from the gui to usable parameters.
%%

global boolean_type_dpoae2 playChanList recChanList boolean_type_range2 hname hear htype_range hratio hf1min hf1max hnum_points hlevel_f1 hlevel_f2 hnum_av hduration htype_dpoae hfs boolean_dpoae_Proc boolean_dpoae_Plot;
global mainFigure check_l hcheck_l hcheck_level age hage check_level name ear type_range ratio f1min f1max num_points level_f1 level_f2 num_av duration type_dpoae fs temp;
boolean_type_range = get(htype_range,'Value');
name = get(hname,'String');
boolean_ear = get(hear,'Value');
age = str2double(get(hage,'String'));
ratio = str2double(get(hratio,'String'));
f1min = str2double(get(hf1min,'String'));
f1max = str2double(get(hf1max,'String'));
num_points = str2double(get(hnum_points,'String'));
level_f1 = str2double(get(hlevel_f1,'String'));
level_f2 = str2double(get(hlevel_f2,'String'));
num_av = str2double(get(hnum_av,'String'));
duration = str2double(get(hduration,'String'));
boolean_type_dpoae = get(htype_dpoae,'Value');
check_level = str2double(get(hcheck_level,'String'));
check_l = str2double(get(hcheck_l,'String'))/1000;
fs = str2double(get(hfs,'String'));
if(boolean_type_range2 == 1)
if (boolean_type_range == 2)
    type_range = 'logari';
end
if (boolean_type_range == 1)
    type_range = 'linear';
end
end
if(boolean_type_range2 == 0)
if (boolean_type_range == 1)
    type_range = 'logari';
end
if (boolean_type_range == 2)
    type_range = 'linear';
end
end

if(boolean_type_dpoae2 == 1)
if (boolean_type_dpoae == 2)
    type_dpoae = '2f1-f2';
end
if (boolean_type_dpoae == 1)
    type_dpoae = '3f1-2f2';
end
end
if(boolean_type_dpoae2 == 0)
if (boolean_type_dpoae == 1)
    type_dpoae = '2f1-f2';
end
if (boolean_type_dpoae == 2)
    type_dpoae = '3f1-2f2';
end
end
if (boolean_ear == 1)
    ear = 'left';
end
if (boolean_ear == 2)
    ear = 'right';
end

close(mainFigure)
playChanList = 1;
recChanList = 2;
checkfit;
dpoae_recording;
end