function maingui_new(~,~)
close all; clear all; %clc; 
global hPinfoText hPatientID hEar hEarText mainguiFigure...
    jbh scLOUT scROUT scIN speakerL speakerR mic_sens

load calibration
scrsize=get(0,'ScreenSize');
mainguiFigure=figure;

color=[205 201 201]/256;

set(mainguiFigure,'OuterPosition',[scrsize(3)/4 30 scrsize(3)/2 scrsize(4)-30],...
    'Color',color)

uicontrol(mainguiFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.1 0.87 0.8 0.1],...
    'BackgroundColor',color,...
    'ForegroundColor','k',...
    'FontSize',20,...
    'String','OAE Measurement System');

uicontrol(mainguiFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.35 0.82 0.3 0.03],...
    'BackgroundColor',color,...
    'Fontsize',12,...
    'String','Patient ID (number > 0):',...
    'HorizontalAlignment','center');
hPatientID = uicontrol(mainguiFigure,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.25 0.78 0.5 0.04],...
    'BackgroundColor','w',...
    'Fontsize',11,...
    'HorizontalAlignment','center');%,...
    %'Callback',@load_info);


jbh = findjobj(handle(hPatientID));
set(jbh, 'KeyPressedCallback',@load_info);


hEar = uicontrol(mainguiFigure,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.25 0.65 0.5 0.1],...
    'BackgroundColor','w',...
    'Fontsize',10,...
    'String',{'Choose ear' 'Left ear' 'Right ear'}',...
    'Value',1,...
    'Callback',@changeFocus);
    
    function changeFocus(~,~)
        val = get(hEar,'Value');
        if val == 2 || val == 3
            uicontrol(tbut);
        end
    end
hPinfo = uipanel(mainguiFigure,...
    'Units','normalized',...
    'Position',[0.2 0.25 0.6 0.3],...
    'Title','Patient Info',...
    'BackgroundColor',color,...
    'FontSize',10);

hPinfoText = uicontrol(hPinfo,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0 0 1 1],...
    'BackgroundColor','w',...
    'FontSize',12,...
    'String','');

hEarText = uicontrol(hPinfo,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0 0.15 1 0.2],...
    'BackgroundColor','w',...
    'ForegroundColor','r',...
    'FontSize',12);

tbut = uicontrol(mainguiFigure,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.15 0.07 0.3 0.1],...
    'String','TEOAE measurement',...
    'FontSize',10,...
    'Callback',{@run_measurement,'TE'});

dbut = uicontrol(mainguiFigure,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.55 0.07 0.3 0.1],...
    'String','DPOAE measurement',...
    'FontSize',10,...
    'Callback',{@run_measurement,'DP'});


uicontrol(hPatientID)
end

function load_info(~,~)
global hPatientID jbh hPinfoText hEar Ear Gender hEarText PatientID ID

PatientID= get(jbh,'Text');
%res=get_patientinfo(PatientID,'../emails/');
tmp = load('../emails/M02.mat');
res = tmp.HearingHistory;

if iscell(res)
    set(hPinfoText,'String',res(2))
else 
    ID = res.ID;
    DoB=['Date of birth: ' sprintf('%g', res.Age(3)) '-' ...
        sprintf('%g', res.Age(2)) '-'...
        sprintf('%g', res.Age(1))];
    patientText={sprintf('\n'); res.Name;...
        res.email;...
        res.Gender;...
        DoB};
    set(hPinfoText,'String',patientText)
    uicontrol(hEar)
        
end
end


function run_measurement(~,~,mtype)
global Ear hEar hEarText hPinfoText hPatientID
    if strcmp(get(hPatientID,'String'),'')
        set(hPinfoText,'String','Enter patient ID')
    else
        if get(hEar,'Value') == 2
            Ear='L';
            set(hEarText,'Visible','off')
        elseif get(hEar,'Value') == 3
            Ear='R';
            set(hEarText,'Visible','off')
        else
            set(hEarText,'String','No ear specified!')
            return
        end
        if strcmp(mtype,'TE') == 1
            teoae_gui;
        elseif strcmp(mtype,'DP') == 1
            dpoae_gui;
        end
    end
end