function txt = myupdatefcn(empt,event_obj)
global f1 f2 f3 Dpoae_level Noise_estimation DpoaeFigure level_f1 level_f2 num_av duration type_dpoae fs;
% Customizes text of data tips

pos = get(event_obj,'Position');
I = find(round(f3)==round(pos(1)));
difference = Dpoae_level(I)-Noise_estimation(I);
if (difference <= 3)
    color_diff = 'r';
else
    color_diff = 'b';
end
txt = {['Frequency: ',num2str(round(pos(1)))] ['Dpoae: ',num2str(Dpoae_level(I))] ['Noise Estimation: ',num2str(Noise_estimation(I))]};     

freq = uicontrol(DpoaeFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.78 0.2 0.2 0.7],...
    'Fontsize',11);
set(freq,'string',{ [' '] [' '] ['Dpoae Frequency: ',num2str(round(pos(1))),' Hz'] [' '] ['Dpoae Level: ',num2str(Dpoae_level(I)),' dB'] [' '] ['Noise Estimation: ',num2str(Noise_estimation(I)),' dB']});

diff = uicontrol(DpoaeFigure,...
    'Style','text',...
    'Units','normalized',...
    'Foregroundcolor',color_diff,...
    'Position',[0.78 0.2 0.2 0.5],...
    'Fontsize',11);
set(diff,'string',{['Difference between Dpoae Level and Noise Estimation: ',num2str(difference),' dB']});


hf1 = uicontrol(DpoaeFigure,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.78 0.2 0.2 0.42],...
    'Fontsize',11);
set(hf1,'string',{['F1: ',num2str(round(f1(I))),' Hz'] ['F1 Level: ',num2str(level_f1),' dB'],...
    [' '] ['F2: ',num2str(round(f2(I))),' Hz'] ['F2 Level: ',num2str(level_f2),' dB'],...
    [' '] ['Ratio: ',num2str(f2(I)/f1(I))] [' '] ['Type of Dpoae: ',type_dpoae],...
    [' '] ['Duration of each stimuli: ',num2str(duration),' s'] [' '] ['Number of averages: ',num2str(num_av)],...
    [' '] ['Sampling Frequency Fs: ',num2str(fs/1000),' KHz'],...
    });

